---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  MATRIX: >-
    [
      {
        "NAME":    "pbf",
        "VERSION": [
            "latest",

            "PBF-latest  PHP-latest",
            "PBF-latest  PHP-8.1",
            "PBF-latest  PHP-8.0",
            "PBF-latest  PHP-7.4",
            "PBF-latest  PHP-7.3",
            "PBF-latest  PHP-7.2",
            "PBF-latest  PHP-7.1",
            "PBF-latest  PHP-7.0",
            "PBF-latest  PHP-5.6",

            "PBF-3  PHP-latest",
            "PBF-3  PHP-8.1",
            "PBF-3  PHP-8.0",
            "PBF-3  PHP-7.4",
            "PBF-3  PHP-7.3",
            "PBF-3  PHP-7.2",
            "PBF-3  PHP-7.1",
            "PBF-3  PHP-7.0",
            "PBF-3  PHP-5.6",

            "PBF-2  PHP-7.4",
            "PBF-2  PHP-7.3",
            "PBF-2  PHP-7.2",
            "PBF-2  PHP-7.1",
            "PBF-2  PHP-7.0",
            "PBF-2  PHP-5.6"
        ],
        "FLAVOUR": ["latest"],
        "ARCH":    ["linux/amd64", "linux/386", "linux/arm64", "linux/arm/v7", "linux/arm/v6"]
      }
    ]


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      matrix:
        description: "The determined version matrix"
        value: ${{ jobs.params.outputs.matrix }}
      refs:
        description: "The determined git ref matrix (only during scheduled run)"
        value: ${{ jobs.params.outputs.refs }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      refs: ${{ steps.set-refs.outputs.matrix }}

    steps:
      - name: "[Set-Output] Matrix"
        id: set-matrix
        run: |
          echo "matrix=$( echo '${{ env.MATRIX }}' | jq -M -c )" >> $GITHUB_OUTPUT

      - name: "[Set-Output] Matrix 'Refs' (master branch and latest tag)"
        id: set-refs
        uses: cytopia/git-ref-matrix-action@v0.1.12
        with:
          repository_default_branch: master
          branches: master
          num_latest_tags: 0
        if: github.event_name == 'schedule'

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Matrix'
          echo '--------------------'
          echo '${{ steps.set-matrix.outputs.matrix }}'
          echo

          echo 'Matrix: Refs'
          echo '--------------------'
          echo '${{ steps.set-matrix-refs.outputs.matrix }}'
          echo
